// .env rendering/parsing + secret generation. The Nostr secret-key (`nsec1…`)
// generator mirrors the repo's cli/gen-nsec.mjs — bech32 of 32 random bytes,
// zero dependencies (only node:crypto), so a fresh box needs nothing
// pre-installed to mint the server's stable save-signing key.
import { randomBytes } from "node:crypto";

/** A short random hex secret, e.g. for the Colyseus monitor password. */
export function genSecret(): string {
  return randomBytes(16).toString("hex");
}

// --- bech32 (NIP-19 / BIP-173) ---
const CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";
const GEN = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3];

function polymod(values: number[]): number {
  let chk = 1;
  for (const v of values) {
    const top = chk >> 25;
    chk = ((chk & 0x1ffffff) << 5) ^ v;
    for (let i = 0; i < 5; i++) if ((top >> i) & 1) chk ^= GEN[i];
  }
  return chk;
}

function hrpExpand(hrp: string): number[] {
  const out: number[] = [];
  for (let i = 0; i < hrp.length; i++) out.push(hrp.charCodeAt(i) >> 5);
  out.push(0);
  for (let i = 0; i < hrp.length; i++) out.push(hrp.charCodeAt(i) & 31);
  return out;
}

function checksum(hrp: string, data: number[]): number[] {
  const values = hrpExpand(hrp).concat(data, [0, 0, 0, 0, 0, 0]);
  const mod = polymod(values) ^ 1;
  const out: number[] = [];
  for (let i = 0; i < 6; i++) out.push((mod >> (5 * (5 - i))) & 31);
  return out;
}

/** Re-group 8-bit bytes into 5-bit groups for the bech32 payload. */
function convertBits(bytes: number[], from: number, to: number, pad: boolean): number[] {
  let acc = 0;
  let bits = 0;
  const out: number[] = [];
  const maxv = (1 << to) - 1;
  for (const value of bytes) {
    acc = (acc << from) | value;
    bits += from;
    while (bits >= to) {
      bits -= to;
      out.push((acc >> bits) & maxv);
    }
  }
  if (pad && bits > 0) out.push((acc << (to - bits)) & maxv);
  return out;
}

function bech32Encode(hrp: string, data: number[]): string {
  const combined = data.concat(checksum(hrp, data));
  let out = hrp + "1";
  for (const d of combined) out += CHARSET.charAt(d);
  return out;
}

/** Mint a fresh Nostr secret key as a bech32 `nsec1…` string. */
export function generateNsec(): string {
  const words = convertBits([...randomBytes(32)], 8, 5, true);
  return bech32Encode("nsec", words);
}

/** Parse a KEY=VALUE .env file body into a map (ignores comments/blank lines). */
export function parseEnv(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

/** Render a .env file body. Skips undefined/empty values. */
export function renderEnv(vars: Record<string, string | undefined>): string {
  const header =
    "# Generated by `gorilator install`. Holds the daemon's listen port, the\n" +
    "# Colyseus monitor password, and the server's stable Nostr save-signing key.\n" +
    "# Keep this file private.\n\n";
  const body = Object.entries(vars)
    .filter(([, v]) => v !== undefined && v !== "")
    .map(([k, v]) => `${k}=${v}`)
    .join("\n");
  return header + body + "\n";
}
