import { describe, expect, it } from "vitest";
import { ROCK_COUNT, WORLD_SIZE } from "./constants";
import { BOULDERS, HOUSE_CENTER, HOUSE_RADIUS, OBSTACLES } from "./obstacles";

// The boulder field is generated by a seeded PRNG (mulberry32) so the server and
// every client agree on the same world. These invariants protect the contract:
// if generation drifts, players desync from the collision map.

describe("BOULDERS (deterministic world generation)", () => {
  it("produces the full requested rock count", () => {
    expect(BOULDERS.length).toBe(ROCK_COUNT);
  });

  it("keeps the central spawn area clear (no boulder within 12 units of origin)", () => {
    for (const b of BOULDERS) {
      expect(Math.hypot(b.x, b.z)).toBeGreaterThanOrEqual(12);
    }
  });

  it("stays within the world range", () => {
    const range = WORLD_SIZE - 12;
    for (const b of BOULDERS) {
      expect(Math.abs(b.x)).toBeLessThanOrEqual(range);
      expect(Math.abs(b.z)).toBeLessThanOrEqual(range);
    }
  });

  it("uses radii within the generator's 1.0..2.2 band", () => {
    for (const b of BOULDERS) {
      expect(b.radius).toBeGreaterThanOrEqual(1.0);
      expect(b.radius).toBeLessThanOrEqual(2.2);
    }
  });

  it("keeps every pair separated by at least the sum of radii + 5", () => {
    for (let i = 0; i < BOULDERS.length; i++) {
      for (let j = i + 1; j < BOULDERS.length; j++) {
        const a = BOULDERS[i];
        const b = BOULDERS[j];
        const dist = Math.hypot(a.x - b.x, a.z - b.z);
        expect(dist).toBeGreaterThanOrEqual(a.radius + b.radius + 5 - 1e-9);
      }
    }
  });
});

describe("OBSTACLES (collision map)", () => {
  it("includes the house footprint at the map centre", () => {
    const house = OBSTACLES.find(
      (o) => o.x === HOUSE_CENTER.x && o.z === HOUSE_CENTER.z && o.radius === HOUSE_RADIUS,
    );
    expect(house).toBeDefined();
  });

  it("contains every boulder", () => {
    for (const b of BOULDERS) {
      expect(OBSTACLES).toContainEqual(b);
    }
  });
});
